apiVersion: v1
kind: ConfigMap
metadata:
  name: loadtest-script
data:
  loadtest.sh: |
    #!/bin/bash
    rm -rf /jmeter/apache-jmeter-*/bin/*.jtl
    rm -rf /jmeter/apache-jmeter-*/bin/*.log
    /jmeter/apache-jmeter-*/bin/jmeter -n -t $1 -l $1-$(date +'%m-%d-%Y')-log.csv -e -o $1-$(date +'%m-%d-%Y')-report/ -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'`
