apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeternode: slave
spec:
  replicas: 2 
  selector:
    matchLabels:
      jmeternode: slave
  template:
    metadata:
      labels:
        jmeternode: slave
    spec:
      serviceAccountName: jmeteruser
      containers:
      - name: jmeter-slave
        image: taylanbakircioglu/jmeter-slave:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1099
        - containerPort: 50000
