FROM alpine:latest

ARG JMETER_VERSION="5.5"
ARG JMETER_PLUGINS_MANAGER="1.8"
ARG	JMETER_DOWNLOAD_URL=https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
ARG	JMETER_PLUGINS_MANAGER_DOWNLOAD_URL="https://jmeter-plugins.org/get/"
ARG LOAD_SCRIPT_PATH="/script"
ARG TZ="Europe/Istanbul"
ARG USER=jmeteruser

ENV JMETER_HOME /jmeter/apache-jmeter-${JMETER_VERSION}
ENV	JMETER_BIN ${JMETER_HOME}/bin
ENV PATH $PATH:$JMETER_BIN

RUN apk update \
  && apk add --update sudo \
  && adduser -D $USER \
  && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
  && chmod 0440 /etc/sudoers.d/$USER \
	&& apk upgrade \
	&& apk add ca-certificates \
	&& update-ca-certificates \
	&& apk add --update openjdk8-jre tzdata curl unzip bash \
	&& apk add --no-cache nss \
	&& rm -rf /var/cache/apk/* \
  && mkdir -p /tmp/dependencies \
	&& curl -L --silent ${JMETER_DOWNLOAD_URL} > /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz \
	&& mkdir -p /jmeter \
  && mkdir -p /script \
	&& tar -xzf /tmp/dependencies/apache-jmeter-${JMETER_VERSION}.tgz -C /jmeter \
	&& rm -rf /tmp/dependencies \
  && chown -R $USER:$USER /jmeter \
  && chown -R $USER:$USER /script

RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/lib/ext/ && wget -q -O jmeter-plugins-manager-${JMETER_PLUGINS_MANAGER}.jar ${JMETER_PLUGINS_MANAGER_DOWNLOAD_URL}

USER $USER
WORKDIR	${JMETER_HOME}
